### ISSUE TITLE
Recommend use of conditional requests (server, client)

### ISSUE THREAD

**Issue by ties** [timbru/draft-sidrops-publication-server-bcp#8]

**Comment by timbru** [comment]
Yeah, we can re-state that here. But the server can't help it if the client doesn't. I am not sure yet whether we should include best practices for polling and fallback in this document. It may be better to revive draft-ietf-sidrops-rpki-rov-timing.

**Comment by timbru** [comment]
Closing because RFC 8182 already says that RPs MUST use conditional requests. So, I don't think we need normative language for clients in this server BCP.
